### ISSUE TITLE
UI Discussion: Milestone 2

### ISSUE THREAD

**Issue by phuanh004** [cse110-sp23-group3/cse110-sp23-group3#46]
Regarding Faith's question on #45. We need to make the app consistent. In case, we change shift all the UI to another theme at the end of this week.

## Task List:

- New Features:
    - [x] #55
- Enhancement:
    - [ ] Design System Figma
    - [x] #56
    - [x] Change font
        - Right now our font is too hard to read.
    - [x] Make the sidebar nicer
    - [x] New chat button
    - [x] #64 , #67?
    - [x] History text field, delete
    - [ ] Loading animation (opt)
    - [ ] #71
- Fix:
    - [x] #37 
    - [x] #41 
    - [x] Re-add the animations

### Design System
- [What is that?](https://help.figma.com/hc/en-us/articles/14552901442839-Overview-Introduction-to-design-systems)
- Why we need one: 
       - Easy to maintain and change all the themes at once.
       - I do have this kind of in our project in the CSS part at `:root` but ppl do not seem to follow that -.-, so I will try to refactor the styling later. However, **We need one for our Figma design**.

**Comment by fnriv** [comment]
would using this font work ? it's the lion king font
https://fontmeme.com/lion-king-font/

**Comment by phuanh004** [comment]
@fnriv that's the uppercase-only font, must be worse 😬.

**Comment by nsyousef** [comment]
Perhaps we could use the Lion King font for things like titles and use one of those simpler fonts for the chat, buttons, etc.

**Comment by phuanh004** [comment]
^ That's a good idea, Nick!
However, loading more than 2 fonts on a page could be expensive on the client side, but I think 2 could be reasonable.

**Comment by ChayPark** [comment]
<img width="808" alt="Screen Shot 2023-06-01 at 1 04 45 PM" src="https://github.com/cse110-sp23-group3/cse110-sp23-group3/assets/99235173/041e6b1a-0d83-41ad-8c0a-feb9fba761a6">

I used the Lionking font for the title and Dosis font for the body.

**Comment by fnriv** [comment]
I wanted to suggest we use [Erode](https://www.fontshare.com/fonts/erode) for the chatbox? a little more elegant and regal.

I created a sample layout with some color and photo changes too-
<img width="882" alt="Screenshot 2023-06-02 at 12 41 02 AM" src="https://github.com/cse110-sp23-group3/cse110-sp23-group3/assets/103224896/8af7f0de-7845-4ad5-b022-85fce673b11f">


I don't think the photo quite communicates mystical - these were the other ones I wanted to use but didn't seem to fit as the top image but we could consider and discuss
![image](https://github.com/cse110-sp23-group3/cse110-sp23-group3/assets/103224896/8b711e12-5b9b-464a-9edc-84a3df28062a)
![image](https://github.com/cse110-sp23-group3/cse110-sp23-group3/assets/103224896/a94afecc-8fe1-424a-9ef7-1a7076d1dcb3)

**Comment by fnriv** [comment]
I know we wanted to discuss a design system though; i think this would be good to do and i'm down to collaborate

**Comment by nsyousef** [comment]
I personally prefer the theme on the left. I think the red speech bubble fits better with the overall theme than the blue one.

As for the background image, maybe we could use the bottom image and crop it so you just see the silhouettes of the animals.

**Comment by lemangomeister** [comment]
Are we set on the fonts?

**Comment by phuanh004** [comment]
> I wanted to suggest we use [Erode](https://www.fontshare.com/fonts/erode) for the chatbox? a little more elegant and regal.
> 
> I created a sample layout with some color and photo changes too- <img alt="Screenshot 2023-06-02 at 12 41 02 AM" width="882" src="https://user-images.githubusercontent.com/103224896/242819688-8af7f0de-7845-4ad5-b022-85fce673b11f.png">
> 
> I don't think the photo quite communicates mystical - these were the other ones I wanted to use but didn't seem to fit as the top image but we could consider and discuss ![image](https://user-images.githubusercontent.com/103224896/242819780-8b711e12-5b9b-464a-9edc-84a3df28062a.png) ![image](https://user-images.githubusercontent.com/103224896/242819818-a94afecc-8fe1-424a-9ef7-1a7076d1dcb3.png)

Looks good on the left faith, the first background looks cool as well so we can do a burry/ glassy like for it as the background. I will try to make a demo for that!

**Comment by fnriv** [comment]
if we have time maybe our loading page could be the animals with the starry sky?

and yes @lemangomeister ; let's finalize our fonts to be **the Lion King font and Erode**

**Comment by phuanh004** [comment]
@fnriv loading page with a large image sounds like a bad idea (cuz the page will load slower).
If it is just a small animated vector like lottiefiles, then it will be better.

**Comment by yujiaen1999** [comment]
@phuanh004

**Comment by yujiaen1999** [comment]
Try set the photo as the background. Keep the original background color and add the image as another layer, then set the image as 30% or 20% transparency. I think they are going to fit our theme. Personally, I prefer the above one.

<img width="1045" alt="Screen Shot 2023-06-03 at 04 24 29" src="https://github.com/cse110-sp23-group3/cse110-sp23-group3/assets/47964649/aa8724f7-3c2d-4159-ae63-e52d72d90101">

**Comment by phuanh004** [comment]
I haven't done it yet but this is how burry looks like if we want something glassy like

<img width="1126" alt="Screenshot 2023-06-03 at 12 46 18 PM" src="https://github.com/cse110-sp23-group3/cse110-sp23-group3/assets/9192184/b5fb25eb-acb6-4c88-9a96-38ccee0ef240">

**Comment by phuanh004** [comment]
> @phuanh004
> 
> I find a cute lion animation in LottieFiles: https://lottiefiles.com/20692-lion
> 
> I think this one could be use for our loading page. (Lion icon, cute, concise)

Could be use this if we have time.

**Comment by lemangomeister** [comment]
> I haven't done it yet but this is how burry looks like if we want something glassy like
> <img alt="Screenshot 2023-06-03 at 12 46 18 PM" width="1126" src="https://user-images.githubusercontent.com/9192184/243128806-b5fb25eb-acb6-4c88-9a96-38ccee0ef240.png">

This actually looks nice! The font colors on the left would just have to be changed to brighter colors to accomodate for the darker background

**Comment by lemangomeister** [comment]
Working on this atm
> New chat button

**Comment by MichaelYe48** [comment]
Working on the sidebar right now.

**Comment by phuanh004** [comment]
@ChayPark @fnriv 
Can you guys give me some feedback on the new UI 😬?

**Comment by lemangomeister** [comment]
> @ChayPark @fnriv Can you guys give me some feedback on the new UI 😬?

I'm not included in the people you're asking but this looks really nice. One thing, is it possible to increase the thickness of the font a bit for "History #", "Settings", and the chat ? They are really small compared to the rest of text on the UI.

**Comment by dolivares11** [comment]
Yeah I like the center chat design, but the left side readability is low. Maybe continue with the yellow background like you did with the buttons?

**Comment by ChayPark** [comment]
> @ChayPark @fnriv
> Can you guys give me some feedback on the new UI 😬?

I think it looks good. One thing is that I can barely see the sidebar features (history, settings). Additionally, should we consider adding a button to hide the sidebar, or should we leave it as it is?

**Comment by phuanh004** [comment]
Thank you for all's input. I changed the blurring and font size. Please take a look again and give feedback how it looks for now!

**Comment by phuanh004** [comment]
> > @ChayPark @fnriv
> > Can you guys give me some feedback on the new UI 😬?
> 
> I think it looks good. One thing is that I can barely see the sidebar features (history, settings). Additionally, should we consider adding a button to hide the sidebar, or should we leave it as it is? If it's preferable to hide the sidebar, I can work on implementing that feature.

I do have it but hide it on desktop

**Comment by phuanh004** [comment]
Close for now since already merge the PR to v2.0.0
