### ISSUE TITLE
Public Vid overview

### ISSUE THREAD

**Issue by fnriv** [cse110-sp23-group3/cse110-sp23-group3#98]
Here are components of the public vid, split into issues.
**all videos are due monday 11:59pm.**

- [x] Team Name and Number
- [x] Brief mention on video or with a picture of each member and their role(s) (i will use photos from our first team vid). if you want to change ur photo let me know
- [x] A quick tour of your product (make that part sizzle to show off any features or things you are proud of) #92 
- [x] A brief retrospective of what challenges you faced, what things you felt you overcame and anything you feel you would do differently now that you are done #93 
- [x] Conclude your video with a brief point of advice for the next students (victims) of 110 projects so they crush the project #94

**Comment by fnriv** [comment]
finished and submitted!
https://youtu.be/jSKOH-n8YdU

**Comment by fnriv** [comment]
https://youtu.be/s6K7DRgyP-M
updated video
