### ISSUE TITLE
Private Vid Overview

### ISSUE THREAD

**Issue by fnriv** [cse110-sp23-group3/cse110-sp23-group3#99]
Here are components of the public vid, split into issues.
**all videos must be sent to faith Tuesday 5pm.**

I might need someone to help me edit this too; we'll discuss in meeting. 

Tasks
- [ ] Team Name and Number
- [ ] Individual member introduction, contribution description, and reflection #91 
- [ ] Repo tour #95 
- [ ] Agile practice discussion #96 
- [ ] Discussion of next steps #97

**Comment by fnriv** [comment]
https://youtu.be/dIMVjVMY8ec
final video
